"""Acceptance as ranking, measured for the first time — on experts graded by construction.

THE CLAIM UNDER TEST. The architecture says a small expert's **acceptance rate against
a larger target** orders experts the way verified quality orders them, so a pool can
be ranked with no judge. `REPORT.md` §6 records that this is the *only* claim that
survives the existence of EAGLE-3 — a purpose-built head wins latency outright and
cannot rank anything. And `docs/RECORD.md` §2 (and `docs/analysis/generated-code-ceiling.md` at the tag `v0.1-foundations`) records why it has
never been tested: **ranking needs experts that differ in quality**, and this project
has had one useful expert. `graded.py` makes three from one corpus.

WHAT IS MEASURED, EXACTLY. Every model here shares one tokenizer with the target
**[ran]** P48, so for the first time acceptance is defined in **tokens** rather than
characters. At temperature 0 the target is one-hot, so speculative decoding's test —
accept with probability min(1, p_target / p_draft) — reduces to *is the drafted token
the target's argmax*. The target is asked for `prompt_logprobs` over the draft it is
handed, and a token is accepted iff its rank under the target is 1. **Nothing is
sampled; nothing is generated by the target during scoring.** One prefill per span.

WHY THE DRAFTER IS SERVED IN CORPUS MODE. `email-full` was trained on transcripts where
a call is immediately followed by its answer — `<tag>…</tag>= {result}` — and served
through `tool_calls` it cannot receive an answer mid-generation, so it **invents one**:
P43's records show `= {"turns": 1, "i_wrote_in_thread": false}` written by the expert
where the tool said `turns: 2, true` **[ran]** `results/P43-openclaw-e2e-20260915/`.
Every later decision in that chain rests on a fact it made up. Scored by a target,
those invented spans would be rejected wholesale, and how much a grade invents is not
its quality. So here the loop is the harness's: generate to `</tag>`, stop, inject the
**real** result, continue. The draft is then the expert's decisions on real facts, and
the same transcript can be handed to the target verbatim.

WHERE THE SIGNAL CAN LIVE, AND WHY IT IS REPORTED IN THREE PLACES. A chain is ~40
tokens of which the verdict is one or two. Acceptance weights every token equally, so
two experts that differ only in verdicts would differ in α by a few percent — and a
result saying "α does not rank" could mean the mechanism fails or that the quality
lives in a token α barely sees. Both are findings; they are different findings. So α
is reported over **all decision tokens** (primary, pre-registered), over the **tag
spans** and over the **verdict span** separately, so the report can say where the
agreement was.

THE HARNESS-SUPPLIED TEXT IS NEVER SCORED. `= {result}` lines are injected by this
loop, exactly as a serving harness would inject them; they sit in the target's prefix
and in no span. Scoring them would score the tool.

    # session A — the instrument, on the expert that exists; no training
    python3 -m training.harness.accept_rank --stage all \\
        --adapter email-full=adapters/email-full --target Qwen/Qwen2.5-32B-Instruct-AWQ
    # session B+C — the graded experts, gated before the target is served
    python3 -m training.harness.accept_rank --stage all \\
        --train g75=training/harness/data_ef/train_g75.jsonl \\
        --train g200=training/harness/data_ef/train_g200.jsonl \\
        --adapter email-full=adapters/email-full --target Qwen/Qwen2.5-32B-Instruct-AWQ
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from training.email.inbox import generate
from training.email.tools import SCHEMA, ToolError, answer
from training.harness import bar
from training.harness.agent_sim import SYSTEM
from training.harness.generate_email_full import listing
from training.harness.generate_email_protocol import INSTRUCTION
from training.harness import suites

EVAL_SEED = 717171     # the suite's own draw; excluded from every corpus by content
EVAL_N = 475           # P43's size, fixed by bar.n_for before that run
CLOSE = ("</thread_history>", "</sender_stats>", "</message>")
TAG = re.compile(r"<(thread_history|sender_stats|message)>([^<]*)</\1>")
OUT = Path("accept_rank.json")
HOST = "http://127.0.0.1:8000"
PROBE = 8              # cases on which an adapter must differ from the base at all


# --- the corpus-mode loop ----------------------------------------------------

def user_text(msg: dict) -> str:
    """The user turn, byte for byte what the corpus generator wrote."""
    return f"{listing(msg)}\n\n{INSTRUCTION}"


# THE ARITY CONVENTION, ON THE WAY IN. P28 renders a single-required-parameter tool
# as `<tag>...</tag>`, so a model that follows the block writes `<thread_history>
# thr-003</thread_history>` — positionally, as told. `agent_sim` maps that body onto
# the parameter's name before the tool sees it; the first version of this loop did
# not, and the untrained 32B had 749 of 1243 calls refused with "is not key=value"
# for obeying the instruction it was given **[ran]** 2026-09-17,
# `session_a_attempt2_positional.json`. Keyed on a COUNT, never on a name.
POSITIONAL = {t["function"]["name"]: (t["function"]["parameters"].get("required")
                                      or sorted(t["function"]["parameters"]["properties"]))[0]
              for t in SCHEMA
              if len(t["function"]["parameters"].get("required")
                     or t["function"]["parameters"]["properties"]) == 1}


def keyed(tool: str, body: str, positional: dict | None = None) -> str:
    """A positional body becomes `param=body` when the tool has exactly one parameter."""
    pos = POSITIONAL if positional is None else positional
    b = body.strip()
    if "=" not in b and tool in pos and b:
        return f"{pos[tool]}={b}"
    return body


def parse_verdict(text: str):
    t = text.upper()
    if "NOT IMPORTANT" in t:
        return False
    if "IMPORTANT" in t:
        return True
    return None


def run_chain(gen, inbox: dict, max_calls: int = 6, suite=None) -> dict:
    """Generate, stop at every closing tag, answer it for real, continue.

    `gen(prefix)` returns the model's continuation after `prefix` (the assistant
    text so far). It is the whole harness, the shape `physics.calc` already has.
    `suite` decides the tags, the tools and the verdict rule; the default is triage.
    """
    close = suite.close if suite else CLOSE
    tag = suite.tag if suite else TAG
    tool = suite.answer if suite else answer
    pos = suite.positional if suite else POSITIONAL
    parse = suite.parse if suite else parse_verdict
    out, spans, calls, refused, stray, malformed = "", [], 0, 0, 0, 0
    for _ in range(max_calls + 1):
        chunk = gen(out)
        # TRUST THE STOP STRING ONLY AS FAR AS IT GOES. Anything past the first
        # closing tag is the model guessing an answer it was told to ask for.
        cuts = [chunk.index(c) + len(c) for c in close if c in chunk]
        cut = min(cuts) if cuts else None
        if cut is not None:
            chunk = chunk[:cut]
        # A `= …` LINE THE MODEL WROTE ITSELF is the invented result P43 saw. It is
        # kept in the span — the target will reject it, which is the point — and
        # counted, so the report can say how often a grade still does it.
        stray += sum(1 for line in chunk.splitlines() if line.lstrip().startswith("="))
        spans.append({"at": len(out), "text": chunk})
        out += chunk
        if cut is None:
            break
        calls += 1
        matches = list(tag.finditer(out))
        # A CLOSING TAG WITH NO CANONICAL OPENING is a malformed call, not a crash.
        # `g25` wrote `<message id=msg-003>…</message>` — the XML-attribute form —
        # and the first version of this loop died on `[-1]` of an empty match list
        # for 209 of 240 cases, recording no text at all **[ran]** P58. The model is
        # told, as it is told about a refused call, and the chain continues.
        if not matches or matches[-1].end() != len(out):
            refused += 1
            malformed += 1
            out += "= ERROR: malformed call — write <tag>key=value</tag>\n"
            continue
        m = matches[-1]                           # the call just closed
        try:
            res = tool(inbox, m.group(1), keyed(m.group(1), m.group(2), pos))
        except ToolError as e:
            refused += 1
            res = f"ERROR: {e}"
        out += f"= {res}\n"
    finished = cut is None
    return {"text": out, "spans": spans, "calls": calls, "refused": refused,
            "malformed": malformed, "stray_results": stray,
            "verdict": parse(spans[-1]["text"]) if finished else None,
            "ran_out": not finished}


# --- serving -------------------------------------------------------------------

def post(path: str, payload: dict, timeout: int = 300) -> dict:
    req = urllib.request.Request(HOST + path, method="POST",
                                 data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)


def serve(model: str, extra: list[str]) -> subprocess.Popen:
    cmd = ["vllm", "serve", model, "--port", "8000", *extra]
    print(f"[rank] {' '.join(cmd)}", flush=True)
    return subprocess.Popen(cmd, stdout=open("vllm.log", "a"), stderr=subprocess.STDOUT)


def wait_ready(proc, minutes: int = 25) -> bool:
    deadline = time.time() + minutes * 60
    while time.time() < deadline:
        if proc.poll() is not None:
            print(f"[rank] the server exited with {proc.returncode}", flush=True)
            return False
        try:
            urllib.request.urlopen(HOST + "/health", timeout=5).read()
            return True
        except Exception:
            time.sleep(5)
    print("[rank] the server never answered /health", flush=True)
    return False


def stop(proc) -> None:
    proc.terminate()
    try:
        proc.wait(timeout=90)
    except subprocess.TimeoutExpired:
        proc.kill()


def completion(model: str, prompt: str, max_tokens: int, close=CLOSE) -> str:
    r = post("/v1/completions", {
        "model": model, "prompt": prompt, "temperature": 0, "max_tokens": max_tokens,
        "stop": list(close), "include_stop_str_in_output": True})
    ch = r["choices"][0]
    text = ch.get("text") or ""
    # BELT AND BRACES ON THE STOP STRING. If the server honoured `stop` but not
    # `include_stop_str_in_output`, `stop_reason` still names the tag it stopped at.
    reason = ch.get("stop_reason")
    if isinstance(reason, str) and reason in close and not text.endswith(reason):
        text += reason
    return text


def stop_check(model: str, prompt: str) -> dict:
    """Does the server stop at a string and hand it back? Tested on a continuation
    the model cannot avoid, so the check cannot fail on the model's phrasing.

    THE FIRST VERSION ASKED THE MODEL TO WRITE A TAG under the triage system prompt.
    The bare base answered `NOT IMPORTANT` — no tag, so no stop, so `stop_included:
    false` — and session A stopped on a check that was measuring the base's
    willingness to write a tag rather than the server's handling of `stop`
    **[ran]** 2026-09-17, one A100 boot for nothing. This one asks it to count and
    stops at `3`: the mechanism, not the model.
    """
    r = post("/v1/completions", {
        "model": model, "prompt": prompt + "1, 2, ", "temperature": 0, "max_tokens": 12,
        "stop": ["3"], "include_stop_str_in_output": True})
    ch = r["choices"][0]
    text = ch.get("text") or ""
    return {"stop_included": text.endswith("3"),
            "stop_reason": ch.get("stop_reason"), "sample": text[:40]}


def preflight(model: str, tok, kind: str) -> dict:
    """One request of each shape before 475 of them. P27 sent 240 that all failed."""
    prompt = tok.apply_chat_template(
        [{"role": "system", "content": "You count."},
         {"role": "user", "content": "Count from 1 to 6, comma separated."}],
        tokenize=False, add_generation_prompt=True)
    out = {"kind": kind}
    if kind in ("draft", "both"):
        chk = stop_check(model, prompt)
        # EITHER PATH IS FINE. A server that returns the stop string, or one that
        # withholds it but names it in `stop_reason` — `completion()` handles both.
        out["stop_included"] = chk["stop_included"] or chk["stop_reason"] == "3"
        out["stop_detail"] = chk
    if kind in ("accept", "both"):
        r = post("/v1/completions", {"model": model, "prompt": prompt + "1, 2, 3",
                                     "max_tokens": 1, "temperature": 0,
                                     "prompt_logprobs": 1})
        pl = (r["choices"][0].get("prompt_logprobs") or [])
        n = len(tok(prompt + "1, 2, 3")["input_ids"])
        out["prompt_logprobs_len"] = len(pl)
        out["prompt_tokens"] = n
        out["shape_ok"] = (len(pl) == n and pl[0] is None
                           and all(isinstance(d, dict) and all("rank" in v for v in d.values())
                                   for d in pl[1:]))
    print(f"[rank] preflight {kind}: {json.dumps(out)[:200]}", flush=True)
    return out


# --- the two stages --------------------------------------------------------------

def draft_arm(model: str, tok, suite, cases: list, max_tokens: int, concurrency: int,
              done: dict, checkpoint) -> list[dict]:
    """Every case through the corpus-mode loop, persisted as it lands."""
    todo = [c for c in cases if c.id not in done]
    print(f"[rank] arm {model}: {len(todo)} to draft, {len(done)} resumed", flush=True)

    def one(case):
        base_prompt = tok.apply_chat_template(
            [{"role": "system", "content": suite.system},
             {"role": "user", "content": suite.user_text(case)}],
            tokenize=False, add_generation_prompt=True)
        try:
            chain = run_chain(lambda prefix: completion(model, base_prompt + prefix,
                                                        max_tokens, suite.close),
                              case.ctx, max_calls=getattr(suite, "max_calls", 6), suite=suite)
        except Exception as e:                      # transport, never folded into a score
            return {"id": case.id, "error": repr(e)[:160]}
        return {"id": case.id, "human": case.human, "truth": case.truth,
                "correct": bool(case.verify(chain["verdict"])), **case.meta,
                "prompt_sha": hashlib.sha256(base_prompt.encode()).hexdigest()[:16],
                **chain}

    t0, n = time.time(), 0
    with ThreadPoolExecutor(max_workers=concurrency) as ex:
        for f in as_completed([ex.submit(one, c) for c in todo]):
            rec = f.result()
            done[rec["id"]] = rec
            n += 1
            if n % 25 == 0 or n == len(todo):
                checkpoint()
                ok = sum(r.get("correct", False) for r in done.values())
                print(f"[rank] arm {model} {len(done)}/{len(cases)} correct {ok} "
                      f"{time.time() - t0:.0f}s", flush=True)
    checkpoint()
    return [done[c.id] for c in cases if c.id in done]


def accepted_flags(prompt_logprobs: list, ids: list[int], start: int) -> list[bool]:
    """Per drafted token: is it the target's rank-1 token at that position?"""
    flags = []
    for i in range(start, len(ids)):
        d = prompt_logprobs[i] or {}
        entry = d.get(ids[i]) or d.get(str(ids[i]))
        flags.append(bool(entry) and entry.get("rank") == 1)
    return flags


def score_span(model: str, tok, prefix: str, span: str) -> dict:
    ids_p = tok(prefix)["input_ids"]
    ids_a = tok(prefix + span)["input_ids"]
    # THE BOUNDARY CAN MERGE. BPE may fuse the last prefix token with the first span
    # token; the span then starts where the two id lists diverge, and the shift is
    # counted rather than hidden.
    k = 0
    while k < len(ids_p) and k < len(ids_a) and ids_p[k] == ids_a[k]:
        k += 1
    r = post("/v1/completions", {"model": model, "prompt": prefix + span,
                                 "max_tokens": 1, "temperature": 0, "prompt_logprobs": 1})
    pl = r["choices"][0].get("prompt_logprobs") or []
    if len(pl) != len(ids_a):
        return {"error": f"prompt_logprobs {len(pl)} != tokens {len(ids_a)}"}
    flags = accepted_flags(pl, ids_a, k)
    lcp = next((i for i, f in enumerate(flags) if not f), len(flags))
    return {"tokens": len(flags), "accepted": sum(flags), "lcp": lcp,
            "shift": len(ids_p) - k, "flags": flags}


def accept_arm(model: str, tok, suite, cases: list, drafts: list[dict], concurrency: int,
               done: dict, checkpoint) -> list[dict]:
    by_id = {c.id: c for c in cases}
    todo = [d for d in drafts if d["id"] not in done and "spans" in d]
    print(f"[rank] accept {len(todo)} drafts, {len(done)} resumed", flush=True)

    def one(d):
        case = by_id[d["id"]]
        base_prompt = tok.apply_chat_template(
            [{"role": "system", "content": suite.system},
             {"role": "user", "content": suite.user_text(case)}],
            tokenize=False, add_generation_prompt=True)
        if hashlib.sha256(base_prompt.encode()).hexdigest()[:16] != d.get("prompt_sha"):
            return {"id": d["id"], "error": "the prompt is not the one the draft saw"}
        scored = []
        for s in d["spans"]:
            if not s["text"]:
                continue
            try:
                scored.append(score_span(model, tok, base_prompt + d["text"][:s["at"]],
                                         s["text"]))
            except Exception as e:
                scored.append({"error": repr(e)[:160]})
        return {"id": d["id"], "spans": scored, **alpha_of(scored)}

    n = 0
    with ThreadPoolExecutor(max_workers=concurrency) as ex:
        for f in as_completed([ex.submit(one, d) for d in todo]):
            rec = f.result()
            done[rec["id"]] = rec
            n += 1
            if n % 25 == 0 or n == len(todo):
                checkpoint()
                print(f"[rank] accept {len(done)}/{len(drafts)}", flush=True)
    checkpoint()
    return [done[d["id"]] for d in drafts if d["id"] in done]


def alpha_of(scored: list[dict]) -> dict:
    """α over all decision tokens, over the tag spans, over the verdict span."""
    ok = [s for s in scored if "tokens" in s]
    if not ok or any("error" in s for s in scored):
        return {"alpha": None, "alpha_tags": None, "alpha_verdict": None,
                "errors": sum("error" in s for s in scored)}
    tot = sum(s["tokens"] for s in ok)
    acc = sum(s["accepted"] for s in ok)
    tags, last = ok[:-1], ok[-1]
    ttot = sum(s["tokens"] for s in tags)
    return {
        "alpha": acc / tot if tot else None,
        "alpha_tags": (sum(s["accepted"] for s in tags) / ttot) if ttot else None,
        "alpha_verdict": last["accepted"] / last["tokens"] if last["tokens"] else None,
        "alpha_lcp": sum(s["lcp"] for s in ok) / tot if tot else None,
        "tokens": tot, "errors": 0,
    }


# --- gates, as code -------------------------------------------------------------

def applied(base: list[dict], adapter: list[dict], n: int = PROBE) -> dict:
    """C18: an adapter vLLM loaded and did not apply serves the base's text."""
    # AN ERRORED RECORD IS NOT A DIFFERENCE. P58's g25 arm failed 209 of 240 requests,
    # its records carried `text: None`, and this gate read None ≠ text as "differs" on
    # 8 of 8 probes — `applied` over an arm that had produced nothing **[ran]**. A
    # check that passes while the capability is broken; only records with a text on
    # both sides are probed, and too few of them is its own verdict.
    b = {r["id"]: r["text"] for r in base if (r.get("text") or "").strip() and "error" not in r}
    a = {r["id"]: r["text"] for r in adapter if (r.get("text") or "").strip() and "error" not in r}
    ids = sorted(set(a) & set(b))[:n]
    differs = sum(a[i] != b[i] for i in ids)
    # EMPTY IS NOT A DIFFERENCE EITHER: an adapter answering "" on every probe reads
    # as `differs` against any base text, and would have called itself applied.
    if len(ids) < 3:
        return {"probed": len(ids), "differs": differs,
                "verdict": f"UNREADABLE: only {len(ids)} probes with non-empty text on both sides"}
    return {"probed": len(ids), "differs": differs,
            "verdict": "applied" if differs else "NOT APPLIED: identical to the base"}


def _map(records: list[dict], key: str = "correct", human_only: bool = True) -> dict:
    return {r["id"]: r[key] for r in records
            if key in r and "error" not in r and (r.get("human") or not human_only)}


def target_gate(target: list[dict], expert: list[dict], majority_bar: float) -> dict:
    """The skill's trap: verify against something not stronger and a high α means
    *drifted least*. FOUNDATIONS §7.2 states the precondition as Q(T) >= max Q(E), and
    the gate follows it literally since 2026-09-17: the target must be **not
    resolvably worse** than the best expert on the same cases, with a total at least
    the expert's. The first version demanded a resolvable *win*, which no target can
    produce against an expert at the ceiling — a tie at the ceiling is a result, not a
    failure of the gate. Neither verdict taken so far changes (2 : 87 and 0 : 8 are
    losses under both rules)."""
    c = bar.compare(_map(target), _map(expert))
    t_acc = c["a_total"] / c["n_paired"] if c["n_paired"] else 0.0
    worse = c["different"] and c["only_b"] > c["only_a"]
    bought = (not worse) and c["a_total"] >= c["b_total"] and t_acc > majority_bar and c["n_paired"] > 0
    ceiling = bought and not c["different"] and c["b_total"] == c["n_paired"]
    return {**c, "target_human_accuracy": round(t_acc, 4), "majority_bar": majority_bar,
            "bought": bought, "tie_at_ceiling": ceiling,
            "reading": ("BOUGHT at the ceiling: the target ties an expert at 1.000 — Q(T) >= max Q(E) holds"
                        if ceiling else
                        "BOUGHT: Q(T) >= max Q(E) on paired cases" if bought else
                        "UNBOUGHT: the target is resolvably worse than the expert — "
                        "acceptance against it would measure similarity, not quality" if worse else
                        "UNBOUGHT: the target's total is below the expert's, or below the bar")}


def grades_gate(arms: dict[str, list[dict]], order: list[str]) -> dict:
    """Are the grades grades? Each adjacent and outer pair, paired on the same cases."""
    pairs = []
    for i in range(len(order)):
        for j in range(i + 1, len(order)):
            lo, hi = order[i], order[j]
            c = bar.compare(_map(arms[hi]), _map(arms[lo]))
            better = hi if c["only_a"] > c["only_b"] else lo
            pairs.append({"pair": [lo, hi], "resolved": c["different"],
                          "better": better if c["different"] else None, **c})
    resolved = [p for p in pairs if p["resolved"]]
    inverted = [p for p in resolved if p["better"] != p["pair"][1]]
    return {"pairs": pairs, "resolved": len(resolved), "inverted": len(inverted),
            "proceed": len(resolved) >= 1,
            "reading": (f"{len(resolved)} of {len(pairs)} pairs resolved by the verifier"
                        + (f"; {len(inverted)} INVERTED (more data scored lower)" if inverted else "")
                        + ("" if resolved else " — the grades are not grades; "
                           "nothing to rank and the target is not served"))}


def ranking_verdict(gate: dict, alphas: dict[str, list[dict]], key: str = "alpha") -> dict:
    """For every pair the verifier resolved: does α order it the same way?"""
    rows = []
    for p in gate["pairs"]:
        if not p["resolved"]:
            continue
        lo, hi = p["pair"]
        better, worse = p["better"], (lo if p["better"] == hi else hi)
        a = _map(alphas[better], key, human_only=False)
        b = _map(alphas[worse], key, human_only=False)
        ids = [i for i in set(a) & set(b) if a[i] is not None and b[i] is not None]
        up = sum(a[i] > b[i] for i in ids)
        down = sum(a[i] < b[i] for i in ids)
        pv = bar.sign_test(up, down)
        state = ("agrees" if pv <= 0.05 and up > down else
                 "DISAGREES" if pv <= 0.05 and down > up else "unresolved")
        rows.append({"pair": [worse, better], "verifier_prefers": better,
                     "alpha_higher": up, "alpha_lower": down, "ties": len(ids) - up - down,
                     "p_value": round(pv, 5), "state": state,
                     "mean_alpha": {better: _mean(a.values()), worse: _mean(b.values())}})
    states = [r["state"] for r in rows]
    verdict = ("SUPPORTED" if rows and all(s == "agrees" for s in states) else
               "FALSIFIED" if "DISAGREES" in states else
               "UNRESOLVED" if rows else "NOTHING TO RANK")
    return {"key": key, "pairs": rows, "verdict": verdict}


def _mean(xs) -> float | None:
    xs = [x for x in xs if x is not None]
    return round(sum(xs) / len(xs), 4) if xs else None


# --- the run ---------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", default="Qwen/Qwen2.5-3B-Instruct")
    ap.add_argument("--adapter", action="append", default=[], help="name=path")
    ap.add_argument("--train", action="append", default=[],
                    help="name=corpus.jsonl — trained in its own process first")
    ap.add_argument("--target", default=None)
    ap.add_argument("--stage", choices=("draft", "accept", "all"), default="all")
    ap.add_argument("--suite", default="email",
                    help="email (triage, 3 tags) or desk[:region] (4 tags, free-text answer)")
    ap.add_argument("--n", type=int, default=None, help="defaults to the suite's own size")
    ap.add_argument("--seed", type=int, default=None, help="defaults to the suite's own draw")
    ap.add_argument("--max-tokens", type=int, default=160)
    ap.add_argument("--concurrency", type=int, default=8)
    ap.add_argument("--max-model-len", type=int, default=4096)
    ap.add_argument("--epochs", type=float, default=3)
    ap.add_argument("--order", default="g75,g200,email-full",
                    help="grades from least to most data, for the ordering test")
    # α AS A DESCRIPTION, NOT A RANKING. When M-target refuses, acceptance against
    # that target cannot order experts by quality — but it still says *where* a small
    # expert agrees with a larger one, token by token. Reviewed 2026-09-17: worth
    # fifteen minutes as a reported number, marked so nobody reads it as a verdict.
    ap.add_argument("--accept-anyway", dest="accept_anyway", action="store_true",
                    help="measure acceptance even if M-target is unbought; the result "
                         "is tagged descriptive and the ranking verdict is not computed")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    if args.out:
        globals()["OUT"] = Path(args.out)

    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.base)

    suite = suites.load(args.suite)
    args.n = args.n or suite.eval_n
    args.seed = args.seed or suite.eval_seed
    results = {"suite": suite.name, "base": args.base, "target": args.target,
               "n": args.n, "seed": args.seed,
               "identity": "accepted iff the drafted token has rank 1 under the target "
                           "at temperature 0; alpha = accepted / drafted decision tokens",
               "started": time.strftime("%Y-%m-%dT%H:%M:%S"), "arms": {}, "accept": {}}
    if OUT.exists():
        try:
            prev = json.loads(OUT.read_text())
            results["arms"] = prev.get("arms", {})
            results["accept"] = prev.get("accept", {})
            print(f"[rank] resuming from {OUT}", flush=True)
        except Exception:
            pass

    def save():
        OUT.write_text(json.dumps(results, indent=2))

    save()
    cases = suite.cases(args.n, args.seed)
    results["cases"] = len(cases)
    results["majority_bar_human"] = suite.bar(cases)
    print(f"[rank] suite {suite.name}: {len(cases)} cases, bar {results['majority_bar_human']:.3f}",
          flush=True)

    # TRAINING IN ITS OWN PROCESS, BEFORE ANY SERVER. train_one.py says why: nothing
    # inside a process releases the CUDA context, and vLLM refused to start beside a
    # trainer that had finished [ran] P53.
    adapters = dict(a.split("=", 1) for a in args.adapter)
    for spec in args.train:
        name, corpus = spec.split("=", 1)
        out_dir = f"adapters/{name}"
        if not Path(out_dir, "adapter_model.safetensors").exists():
            print(f"[rank] training {name} from {corpus}", flush=True)
            rc = subprocess.call([sys.executable, "-m", "training.code.train_one",
                                  "--base", args.base, "--train", corpus,
                                  "--out-dir", out_dir, "--epochs", str(args.epochs)])
            if rc != 0:
                results["stopped"] = f"training {name} failed rc={rc}"
                save()
                return 1
        adapters[name] = out_dir

    def arm_records(name):
        return list(results["arms"].get(name, {}).get("records", {}).values())

    if args.stage in ("draft", "all"):
        extra = ["--max-model-len", str(args.max_model_len),
                 "--gpu-memory-utilization", "0.90"]
        if adapters:
            extra += ["--enable-lora", "--max-lora-rank", "16",
                      "--max-loras", str(len(adapters)),
                      "--lora-modules", *[f"{k}={v}" for k, v in adapters.items()]]
        p = serve(args.base, extra)
        try:
            if not wait_ready(p):
                results["stopped"] = "the base never came up"; save(); return 1
            results["preflight_base"] = preflight(args.base, tok, "draft")
            if not results["preflight_base"]["stop_included"]:
                results["stopped"] = "the server does not stop at a closing tag"; save(); return 1
            for name, model in [("base", args.base)] + [(k, k) for k in adapters]:
                arm = results["arms"].setdefault(name, {"model": model, "records": {}})
                recs = draft_arm(model, tok, suite, cases, args.max_tokens,
                                 args.concurrency, arm["records"], save)
                arm.update(summarise(recs))
                if name != "base":
                    arm["applied"] = applied(arm_records("base"), recs)
                    print(f"[rank] gate {name}: {arm['applied']['verdict']}", flush=True)
                save()
        finally:
            stop(p)

    if args.target and args.stage in ("draft", "accept", "all"):
        order = [g for g in args.order.split(",") if g in results["arms"]]
        # THE GRADES GATE RUNS BEFORE THE TARGET IS SERVED. If the verifier cannot
        # order the grades there is nothing for acceptance to agree with, and the
        # 19 GB download buys nothing.
        if len(order) >= 2:
            results["grades_gate"] = grades_gate(
                {g: arm_records(g) for g in order}, order)
            print(f"[rank] grades: {results['grades_gate']['reading']}", flush=True)
            save()
            if not results["grades_gate"]["proceed"]:
                results["stopped_at_gate"] = "grades"; results["finished"] = time.strftime(
                    "%Y-%m-%dT%H:%M:%S"); save(); return 0

        extra = ["--max-model-len", str(args.max_model_len),
                 "--gpu-memory-utilization", "0.90", "--no-enable-prefix-caching"]
        p = serve(args.target, extra)
        try:
            if not wait_ready(p):
                results["stopped"] = "the target never came up"; save(); return 1
            from transformers import AutoTokenizer as AT
            ttok = AT.from_pretrained(args.target)
            results["chat_template_identical"] = (ttok.chat_template == tok.chat_template)
            if not results["chat_template_identical"]:
                results["stopped"] = "the target's chat template differs: the prompt would not be the one the draft saw"
                save(); return 1
            results["preflight_target"] = preflight(args.target, tok, "both")
            if not results["preflight_target"].get("shape_ok"):
                results["stopped"] = "prompt_logprobs did not come back in the shape the scorer reads"
                save(); return 1
            # HEADROOM: the target triages the same inbox, the same way.
            arm = results["arms"].setdefault("target", {"model": args.target, "records": {}})
            recs = draft_arm(args.target, tok, suite, cases, args.max_tokens,
                             args.concurrency, arm["records"], save)
            arm.update(summarise(recs)); save()
            best = order[-1] if order else next((k for k in adapters), None)
            if best:
                results["target_gate"] = target_gate(recs, arm_records(best),
                                                     results["majority_bar_human"])
                print(f"[rank] target: {results['target_gate']['reading']}", flush=True)
                save()
                if not results["target_gate"]["bought"] and not args.accept_anyway:
                    results["stopped_at_gate"] = "target"
                    results["finished"] = time.strftime("%Y-%m-%dT%H:%M:%S"); save()
                    return 0
                if not results["target_gate"]["bought"]:
                    results["descriptive"] = ("acceptance measured against a target M-target "
                                              "refused: it describes agreement and RANKS NOTHING")
                    print(f"[rank] {results['descriptive']}", flush=True)
            # ACCEPTANCE, over every drafted arm.
            for name in ["base"] + list(adapters):
                if name not in results["arms"]:
                    continue
                acc = results["accept"].setdefault(name, {"records": {}})
                scored = accept_arm(args.target, tok, suite, cases, arm_records(name),
                                    args.concurrency, acc["records"], save)
                acc.update(summarise_alpha(scored)); save()
                print(f"[rank] alpha {name}: {json.dumps({k: v for k, v in acc.items() if k != 'records'})}",
                      flush=True)
        finally:
            stop(p)

        if "grades_gate" in results and not results.get("descriptive"):
            alphas = {g: list(results["accept"].get(g, {}).get("records", {}).values())
                      for g in order}
            results["ranking"] = {k: ranking_verdict(results["grades_gate"], alphas, k)
                                  for k in ("alpha", "alpha_tags", "alpha_verdict", "alpha_lcp")}
            print(f"[rank] verdict alpha: {results['ranking']['alpha']['verdict']}", flush=True)
        if "email-full" in results["accept"]:
            results["within_expert"] = within_expert(arm_records("email-full"),
                                                     list(results["accept"]["email-full"]["records"].values()))

    results["finished"] = time.strftime("%Y-%m-%dT%H:%M:%S")
    save()
    return 0


def summarise(recs: list[dict]) -> dict:
    ok = [r for r in recs if "error" not in r]
    hum = [r for r in ok if r.get("human")]
    return {"n": len(recs), "errors": len(recs) - len(ok),
            "correct": sum(r["correct"] for r in ok),
            "accuracy": round(sum(r["correct"] for r in ok) / len(ok), 4) if ok else None,
            "human_n": len(hum), "human_correct": sum(r["correct"] for r in hum),
            "human_accuracy": round(sum(r["correct"] for r in hum) / len(hum), 4) if hum else None,
            "undecided": sum(r["verdict"] is None for r in ok),
            "calls": sum(r["calls"] for r in ok), "refused": sum(r["refused"] for r in ok),
            "stray_results": sum(r.get("stray_results", 0) for r in ok),
            "malformed": sum(r.get("malformed", 0) for r in ok),
            "partial": False}


def summarise_alpha(recs: list[dict]) -> dict:
    ok = [r for r in recs if r.get("alpha") is not None]
    return {"n": len(recs), "errors": sum(1 for r in recs if r.get("alpha") is None),
            "alpha": _mean(r["alpha"] for r in ok),
            "alpha_tags": _mean(r["alpha_tags"] for r in ok),
            "alpha_verdict": _mean(r["alpha_verdict"] for r in ok),
            "alpha_lcp": _mean(r["alpha_lcp"] for r in ok),
            "tokens": sum(r["tokens"] for r in ok)}


def within_expert(drafts: list[dict], alphas: list[dict]) -> dict:
    """Reported, not gated: inside one expert, is α higher where it was right?"""
    a = {r["id"]: r["alpha"] for r in alphas if r.get("alpha") is not None}
    right = [a[r["id"]] for r in drafts if r["id"] in a and r.get("correct")]
    wrong = [a[r["id"]] for r in drafts if r["id"] in a and not r.get("correct")]
    return {"alpha_when_correct": _mean(right), "alpha_when_wrong": _mean(wrong),
            "n_correct": len(right), "n_wrong": len(wrong)}


if __name__ == "__main__":
    raise SystemExit(main())
